### ISSUE TITLE
Change all Shell Script aliases to Bash

### ISSUE THREAD

**Issue by ihodev** [ihodev/a-file-icon#146]
https://github.com/sublimehq/Packages/blob/master/ShellScript/Bash.sublime-syntax

**Comment by rwols** [comment]
Hello there! Today I noticed the .gitignore syntax seems a bit off. What you probably want for `Shell Script (Git).sublime-syntax` is this now:
```
contexts:
  prototype:
    - include: scope:source.shell.bash#prototype
  main:
    - include: scope:source.shell.bash#expansion-pattern
```
